Repository JONGSKY/Thunder-search-system, pull requests merged in 2020-12, with the labels that each got.

#83 SET #82 - 최종프로젝트 README.md 파일 수정
  README.md
Labels: 🌈 enhancement

#84 SET #85 - 프로젝트에 적한한 LICENSE 생성
  LICENSE.txt
Labels: 🌈 enhancement, 🏍Simple, 💻Developing, 🧵 environment

#87 SET #86 - 최종프로젝트 README.md 파일 수정
  README.md
Labels: 🌈 enhancement, 🧵 environment

#89 SET #88 - 구글 드라이브 다운로드 링크 수정
  README.md
Labels: 🏍Simple
